boys = ['AJITH','PRIGES','AB','ARUNMATHAVAN','CHANDRU','NIMAL','GB','HARIHARAN','HARRISH','JAYANTHAN', 'KARTHICK','MAGESH','ISHAAQ','NIRMAL','PANNEER','PRAVEEN','RAMASAMY','RAJESH','SIVA','TAMIL','VJ','ZABI','AKASH','ARUL','KAMESH','KESAVA','SURESH','RIJOE']
girls = ['ABINAYA','AKSHARA','BANUMATHI','GEMSHA','HARSIKA','INDIRA','JUMANA', 'KEERTHIKA','KENISHIYA','FENCY','JASMINE','MURSHIDHA','MUSITHA','RETHINA','PRIYA','RAKSHANAA','REVATHY','SANDHYA','SHOBANAA','UMABHARATHI','VAIDHEHI','VAISHNAVI','VASANTHA','SARANYA','SHAKITHYA','CHRISTAL','ASHA','SIVARANJANI','NIBYSHA']

from cs50 import SQL

db = SQL("sqlite:///survey.db")

All = []
det = db.execute("Select name from StudentD")
for name in det:
    All.append(name['name'])




subjects=['DBMS', 'MATHS', 'OS', 'CA', 'DAA', 'SE']



